def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
  source = [
      'regression_base.cpp',
      'passive_aggressive.cpp',
      'regression_factory.cpp'
      ]
  headers = [
      'regression_base.hpp',
      'regression_factory.hpp',
      'regression.hpp',
      'passive_aggressive.hpp',
      ]
  use = ['PFICOMMON']
  bld.core_sources.extend(bld.add_prefix(source))
  bld.core_headers.extend(bld.add_prefix(headers))
  bld.core_use.extend(use)

  def make_test(s):
      bld.program(
          features = 'gtest',
          source = s,
          target = s[0: s.rfind('.')],
          includes = '.',
          use = 'PFICOMMON MSGPACK jubatus_core'
          )

  test_source = [
      'regression_test.cpp',
      'regression_factory_test.cpp',
      ]
  for s in test_source:
      make_test(s)

  bld.install_files('${PREFIX}/include/jubatus/core/regression', [
      'regression_base.hpp',
      'regression_factory.hpp',
      ])
