def options(opt):
  pass

def configure(conf):
  pass

def build(bld):

  headers = [
      'mixable.hpp',
      ]
  bld.core_headers.extend(bld.add_prefix(headers))

  def make_test(t):
    bld.program(
      features='gtest',
      source=t + '.cpp',
      target=t,
      includes='.',
      use='PFICOMMON MSGPACK jubatus_core',
      )

  tests = [
    'mixable_test',
    ]

  for t in tests:
    make_test(t)
