def options(opt):
  pass

def configure(conf):
  pass

def build(bld):
  source = [
      'linear_mixable.cpp',
      'linear_function_mixer.cpp',
      'mixable_weight_manager.cpp',
      'model.cpp',
      ]

  header = [
      'linear_mixable.hpp',
      'mixable.hpp',
      'model.hpp',
      'diffv.hpp',
      'linear_function_mixer.hpp',
      'mixable_weight_manager.hpp',
      ]
  bld.core_sources.extend(bld.add_prefix(source))
  bld.core_headers.extend(bld.add_prefix(header))

  def make_test(t):
    bld.program(
      features='gtest',
      source=t + '.cpp',
      target=t,
      includes='.',
      use='PFICOMMON MSGPACK jubatus_core',
      )

  tests = [
    'mixable_test',
    'model_test',
    'linear_function_mixer_test',
    ]

  for t in tests:
    make_test(t)
