def options(ctx):
  pass

def configure(ctx):
  pass

def build(bld):
  source = [
    'anomaly_base.cpp',
    'anomaly_factory.cpp',
    'lof.cpp',
    'lof_storage.cpp',
    ]
  headers = [
      'anomaly_base.hpp',
      'anomaly_factory.hpp',
      'anomaly_type.hpp',
      'anomaly_storage_base.hpp',
      'lof.hpp',
      'lof_storage.hpp',
      ]
  use = ['PFICOMMON']

  bld.core_sources.extend(bld.add_prefix(source))
  bld.core_headers.extend(bld.add_prefix(headers))
  bld.core_use.extend(use)

  def make_test(s):
    bld.program(
      features = 'gtest',
      source = s,
      target = s[0:s.rfind('.')],
      includes = '.',
      use = 'PFICOMMON jubatus_core')

  map(make_test, [
      'lof_storage_test.cpp',
      'lof_test.cpp'
      ])

