def options(opt):
  pass

def configure(conf):
  pass

def build(bld):
  source = [
      'classifier.cpp',
      'regression.cpp',
      'recommender.cpp',
      'stat.cpp',
      'anomaly.cpp',
      'graph.cpp',
      'linear_function_mixer.cpp',
      'mixable_weight_manager.cpp',
      ]
  header = [
      'classifier.hpp',
      'regression.hpp',
      'recommender.hpp',
      'stat.hpp',
      'anomaly.hpp',
      'graph.hpp',
      'diffv.hpp',
      'linear_function_mixer.hpp',
      'mixable_weight_manager.hpp',
      ]
  use = ['PFICOMMON', 'MSGPACK']

  bld.core_sources.extend(bld.add_prefix(source))
  bld.core_headers.extend(bld.add_prefix(header))
  bld.core_use.extend(use)

  def make_test(t):
    bld.program(
      features='gtest',
      source=t + '.cpp',
      target=t,
      includes='.',
      use='PFICOMMON MSGPACK jubatus_core'
      )

  tests = [
    'linear_function_mixer_test',
    'anomaly_test',
    'classifier_test',
    'graph_test',
    'regression_test',
    'recommender_test',
    'stat_test',
    ]

  for t in tests:
    make_test(t)
