def options(opt): pass
def configure(conf): pass

def build(bld):
  source = [
      'stat.cpp',
      'mixable_stat.cpp'
      ]
  headers = [
      'stat.hpp',
      'mixable_stat.hpp',
      ]
  use = ['PFICOMMON', 'MSGPACK']

  bld.core_sources.extend(bld.add_prefix(source))
  bld.core_headers.extend(bld.add_prefix(headers))
  bld.core_use.extend(use)

  bld.program(
    features = 'gtest',
    source = [
      'stat_test.cpp', 'mixable_stat_test.cpp'
      ],
    target = 'stat_test',
    includes = '.',
    use = 'PFICOMMON MSGPACK jubatus_core'
    )
