import Options

subdirs = "common anomaly classifier framework fv_converter graph recommender regression stat storage"

def options(opt):
  opt.recurse(subdirs)

def configure(conf):
  conf.recurse(subdirs)

def build(bld):
  bld.recurse(subdirs)
