import Options

subdirs = "common anomaly classifier framework fv_converter graph recommender regression stat storage"

def options(opt):
  opt.recurse(subdirs)

def configure(conf):
  conf.recurse(subdirs)

def build(bld):

  source = [
      'version.cpp',
      ]
  headers = [
      'version.hpp',
      ]

  bld.core_sources.extend(bld.add_prefix(source))
  bld.core_headers.extend(bld.add_prefix(headers))

  bld.recurse(subdirs)
